plugins {
    id 'com.android.library'
}

android {
    namespace 'com.paddle.ocr'
    compileSdk 37
    defaultConfig { minSdk 31 }
    buildTypes {
        release {
            minifyEnabled false
            consumerProguardFiles 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.24.3'
    implementation 'com.quickbirdstudios:opencv:4.5.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0'
    implementation 'androidx.core:core-ktx:1.17.0'
}
