plugins { id 'com.android.application' }

android {
    namespace 'com.yagay.floatlens'
    compileSdk 37

    defaultConfig {
        applicationId 'com.yagay.floatlens'
        minSdk 31
        targetSdk 37
        versionCode 30
        versionName '2.4.0'
    }
    buildFeatures {
        buildConfig true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core:1.17.0'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'com.google.mlkit:text-recognition:16.0.1'
    implementation 'com.google.mlkit:text-recognition-chinese:16.0.1'
}
